name: Run tests
on:
  pull_request:
    branches: [main]
jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v2
      - name: 🔖 Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "15"
      - name: 🔧 Install
        run: npm install
      - name: 🧪 Test
        run: npm test
